export const MAKE_REQUEST = 'MAKE_REQUEST'
export const FAIL_REQUEST = 'FAIL_REQUEST'
export const GET_TASK_LIST = 'GET_TASK_LIST'
export const DELETE_TASK = 'DELETE_TASK'
export const CREATE_TASK = 'CREATE_TASK'
export const UPDATE_TASK = 'UPDATE_TASK'
export const GET_TASK_OBJ = 'GET_TASK_OBJ'